from . import NERPosNo
import unittest
import os
# Text analysis
text_analysis = {
                    'interjs': [u'familieoverhodet'],
                    'inf_merks': [],
                    'conjs': [u'og', u'men', u's\xe5'],
                    'substs': [u'G\xe5rden', u'Andreas', u'Faren', u'sm\xe5brukeren', u'boksamling', u's\xf8nn', u'fransk', u'engelsk', u'g\xe5rdsarbeid', u'\xc5sen', u'Jonsson', u'g\xe5rden', u'Bibelen', u'Aarflot', u'norr\xf8nt', u'konfirmasjonen', u'foreldrene', u'Ekset', u'evnene', u'bruk', u'Aarflots', u'Sivert', u'sunnm\xf8rsdialekten', u'Hovdebygda', u'Rasmus', u'kamerater', u'formen', u'latin', u'Ivar', u'garden', u'b\xf8kene', u'slektskap', u'observasjoner', u'Iver', u'kirkeboken', u'foreldrenes', u'familien', u'broren', u'\xabIvar\xbb', u'Aasen', u'i', u'Sunnm\xf8re', u'presten', u's\xf8sken', u'frav\xe6r', u'kilometer'],
                    'unknowns': [], 'verbs': [u'satte', u'mistet', u'gjort', u'utvikle', u'hadde', u'kom', u'skrev', u'd\xf8de', u'f\xf8rte', u'lot', u'var', u'vokste', u'inspirert', u'kan', u'l\xe6rte', u'd\xf8pt', u'ha', u'f\xf8dt', u'isolert', u'leste', u'ble', u'utmerket'],
                    'numbers': [],
                    'props': [u'Iver', u'Bibelen', u'Andreas', u'Ivar', u'Aasen', u'Aarflot', u'\xabIvar\xbb', u'Sivert', u'Sunnm\xf8re', u'Aarflots', u'Ekset', u'\xc5sen', u'Hovdebygda', u'Rasmus', u'Jonsson'], 'dets': [u'de', u'begge', u'ingen', u'1826', u'Det', u'\xe5tte', u'3', u'1845', u'den', u'det', u'sine'],
                    'sbus': [],
                    'adj': [u'nye', u'f\xe5', u'gammelnorsk', u'intellektuelle', u'tidlig', u'mye', u'unge', u'rosende'],
                    'obt': [
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Ivar', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Ivar', u'subst', u'prop', u'mask'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Ivar subst prop mask', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Aasen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Aasen', u'subst', u'prop', u'<*sen>', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Aasen subst prop <*sen> <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ble', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'bli', u'verb', u'pret', u'i2', u'tr5', u'a5', u'pa4/til', u'pr1', u'pr2', u'<aux1/perf_part>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'bli verb pret i2 tr5 a5 pa4/til pr1 pr2 <aux1/perf_part>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'f\xf8dt', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'f\xf8de', u'verb', u'perf-part', u'tr1', u'i1'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'f\xf8de verb perf-part tr1 i1', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'p\xe5', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'p\xe5', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'p\xe5 prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'g\xe5rden', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'g\xe5rd', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'g\xe5rd subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'\xc5sen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'\xc5sen', u'subst', u'prop', u'<*sen>', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'\xc5sen subst prop <*sen> <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'i', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'i', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'i prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Hovdebygda', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Hovdebygda', u'subst', u'prop', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Hovdebygda subst prop <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'p\xe5', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'p\xe5', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'p\xe5 prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Sunnm\xf8re', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Sunnm\xf8re', u'subst', u'prop', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Sunnm\xf8re subst prop <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'som', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'som', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'som prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u's\xf8nn', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u's\xf8nn', u'subst', u'appell', u'mask', u'ub', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u's\xf8nn subst appell mask ub ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'av', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'av', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'av prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'sm\xe5brukeren', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'sm\xe5bruker', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'sm\xe5bruker subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Ivar', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Ivar', u'subst', u'prop', u'mask', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Ivar subst prop mask <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Jonsson', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Jonsson', u'subst', u'prop', u'<*son>', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Jonsson subst prop <*son> <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Han', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'nom'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 nom', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ble', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'bli', u'verb', u'pret', u'i2', u'tr5', u'a5', u'pa4/til', u'pr1', u'pr2', u'<aux1/perf_part>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'bli verb pret i2 tr5 a5 pa4/til pr1 pr2 <aux1/perf_part>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'd\xf8pt', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'd\xf8pe', u'verb', u'perf-part', u'tr1'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'd\xf8pe verb perf-part tr1', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Iver', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Iver', u'subst', u'prop', u'mask', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Iver subst prop mask <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Andreas', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Andrea', u'subst', u'prop', u'fem', u'gen', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Andrea subst prop fem gen <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'formen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'form', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'form subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'\xabIvar\xbb', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Ivar', u'subst', u'prop', u'mask'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Ivar subst prop mask', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'kom', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'komme', u'verb', u'pret', u'i1', u'i2', u'tr11', u'a3', u'pa4', u'rl5', u'pa5', u'tr12', u'a4', u'rl15', u'tr21', u'tr22'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'komme verb pret i1 i2 tr11 a3 pa4 rl5 pa5 tr12 a4 rl15 tr21 tr22', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'i', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'i', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'i prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'bruk', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'bruk', u'subst', u'appell', u'mask', u'ub', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'bruk subst appell mask ub ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'omkring', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'omkring', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'omkring prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'1845', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': True, 'roman': False, 'quantity': True}, 'is_det': True, 'tagging': [u'1845', u'det', u'fl', u'kvant'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'1845 det fl kvant', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'G\xe5rden', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'g\xe5rd', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'g\xe5rd subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'han', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'akk'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 akk', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'vokste', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'vokse', u'verb', u'pret', u'i2', u'pa4', u'tr12', u'rl14', u'pa4/til', u'pr6'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'vokse verb pret i2 pa4 tr12 rl14 pa4/til pr6', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'opp', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'opp', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'opp prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'p\xe5', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'p\xe5', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'p\xe5 prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'var', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'v\xe6re', u'verb', u'pret', u'a5', u'pr1', u'pr2', u'<aux1/perf_part>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'v\xe6re verb pret a5 pr1 pr2 <aux1/perf_part>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'isolert', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'isolere', u'verb', u'perf-part', u'tr1', u'rl4'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'isolere verb perf-part tr1 rl4', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u's\xe5', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u's\xe5', u'konj', u'clb'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u's\xe5 konj clb', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'han', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'akk'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 akk', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'hadde', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ha', u'verb', u'pret', u'pa1', u'd5', u'a6', u'tr12', u'rl6', u'pa3', u'tr6', u'd6/til', u'<aux1/perf_part>', u'pa6'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ha verb pret pa1 d5 a6 tr12 rl6 pa3 tr6 d6/til <aux1/perf_part> pa6', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ingen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': True, 'roman': False, 'quantity': True}, 'is_det': True, 'tagging': [u'ingen', u'det', u'fl', u'kvant'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ingen det fl kvant', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'kamerater', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'kamerat', u'subst', u'appell', u'mask', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'kamerat subst appell mask ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Dette', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'dette', u'pron', u'n\xf8yt', u'ent', u'pers', u'3'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'dette pron n\xf8yt ent pers 3', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'f\xf8rte', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'f\xf8re', u'verb', u'pret', u'tr1', u'pa1', u'rl4', u'a6', u'a7', u'a12', u'pa3', u'tr12/til', u'a2'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'f\xf8re verb pret tr1 pa1 rl4 a6 a7 a12 pa3 tr12/til a2', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'til', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'til', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'til prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'at', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'at', u'sbu'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'at sbu', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'han', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'akk'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 akk', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'leste', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'lese', u'verb', u'pret', u'tr1', u'i1', u'tr11', u'pa1'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'lese verb pret tr1 i1 tr11 pa1', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'mye', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'mye', u'adj', u'n\xf8yt', u'ub', u'ent', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'mye adj n\xf8yt ub ent pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'i', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'i', u'subst', u'appell', u'mask', u'ub', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'i subst appell mask ub ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'de', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'de', u'pron', u'fl', u'pers', u'3', u'nom'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'de pron fl pers 3 nom', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'f\xe5', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'f\xe5', u'adj', u'fl', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'f\xe5 adj fl pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'b\xf8kene', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'b\xf8k', u'subst', u'appell', u'mask', u'be', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'b\xf8k subst appell mask be fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'familien', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'familie', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'familie subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'hadde', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ha', u'verb', u'pret', u'pa1', u'd5', u'a6', u'tr12', u'rl6', u'pa3', u'tr6', u'd6/til', u'<aux1/perf_part>', u'pa6'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ha verb pret pa1 d5 a6 tr12 rl6 pa3 tr6 d6/til <aux1/perf_part> pa6', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'deriblant', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'deriblant', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'deriblant prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Bibelen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Bibelen', u'subst', u'prop', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Bibelen subst prop <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Faren', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'fare', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'fare subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'd\xf8de', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'd\xf8', u'verb', u'pret', u'i2', u'tr6'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'd\xf8 verb pret i2 tr6', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'i', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'i', u'subst', u'appell', u'mask', u'ub', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'i subst appell mask ub ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'1826', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': True, 'roman': False, 'quantity': True}, 'is_det': True, 'tagging': [u'1826', u'det', u'fl', u'kvant'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'1826 det fl kvant', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Det', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': True, 'tagging': [u'det', u'pron', u'n\xf8yt', u'ent', u'pers', u'3'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'det pron n\xf8yt ent pers 3', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'var', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'v\xe6re', u'verb', u'pret', u'a5', u'pr1', u'pr2', u'<aux1/perf_part>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'v\xe6re verb pret a5 pr1 pr2 <aux1/perf_part>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'\xe5tte', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': True, 'roman': False, 'quantity': True}, 'is_det': True, 'tagging': [u'\xe5tte', u'det', u'fl', u'kvant'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'\xe5tte det fl kvant', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u's\xf8sken', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u's\xf8sken', u'subst', u'appell', u'n\xf8yt', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u's\xf8sken subst appell n\xf8yt ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj', u'clb'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj clb', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'de', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'de', u'pron', u'fl', u'pers', u'3', u'nom'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'de pron fl pers 3 nom', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'mistet', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'miste', u'verb', u'pret', u'tr5'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'miste verb pret tr5', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'begge', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': True, 'roman': False, 'quantity': True}, 'is_det': True, 'tagging': [u'begge', u'det', u'fl', u'kvant'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'begge det fl kvant', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'foreldrene', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'forelder', u'subst', u'appell', u'mask', u'be', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'forelder subst appell mask be fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'tidlig', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'tidlig', u'adj', u'n\xf8yt', u'ub', u'ent', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'tidlig adj n\xf8yt ub ent pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'I', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'i', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'i prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'foreldrenes', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'forelder', u'subst', u'appell', u'mask', u'be', u'fl', u'gen'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'forelder subst appell mask be fl gen', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'frav\xe6r', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'frav\xe6r', u'subst', u'appell', u'n\xf8yt', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'frav\xe6r subst appell n\xf8yt ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ble', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'bli', u'verb', u'pret', u'i2', u'tr5', u'a5', u'pa4/til', u'pr1', u'pr2', u'<aux1/perf_part>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'bli verb pret i2 tr5 a5 pa4/til pr1 pr2 <aux1/perf_part>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'broren', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'bror', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'bror subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'det', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': True, 'tagging': [u'det', u'det', u'dem', u'n\xf8yt', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'det det dem n\xf8yt ent', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'nye', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ny', u'adj', u'be', u'ent', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'ny adj be ent pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'familieoverhodet', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'familieoverhodet', u'interj'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': True, 'options': u'familieoverhodet interj', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u';', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$;', u'clb', u'<semi>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$; clb <semi>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'han', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'akk'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 akk', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'satte', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'sette', u'verb', u'pret', u'tr1', u'pa1', u'rl4', u'pa2', u'a6', u'pa5', u'rl6', u'pa1/til', u'pa3', u'a9', u'tr23'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'sette verb pret tr1 pa1 rl4 pa2 a6 pa5 rl6 pa1/til pa3 a9 tr23', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Ivar', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Ivar', u'subst', u'prop', u'mask', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Ivar subst prop mask <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'til', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'til', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'til prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'g\xe5rdsarbeid', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'g\xe5rdsarbeid', u'subst', u'appell', u'n\xf8yt', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'g\xe5rdsarbeid subst appell n\xf8yt ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj', u'clb'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj clb', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'lot', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'late', u'verb', u'pret', u'tr1', u'tr21/til', u'tr22/til', u'a16', u'rl20', u'a17'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'late verb pret tr1 tr21/til tr22/til a16 rl20 a17', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ham', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'akk'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 akk', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ikke', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ikke', u'adv'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ikke adv', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'utvikle', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'utvikle', u'verb', u'inf', u'tr1', u'rl5', u'rl10/til'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'utvikle verb inf tr1 rl5 rl10/til', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'de', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': True, 'tagging': [u'de', u'det', u'dem', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'de det dem fl', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'intellektuelle', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'intellektuell', u'adj', u'fl', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'intellektuell adj fl pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'evnene', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'evne', u'subst', u'appell', u'mask', u'be', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'evne subst appell mask be fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'sine', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': True, 'tagging': [u'sin', u'det', u'fl', u'poss'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'sin det fl poss', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'men', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'men', u'konj', u'clb'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'men konj clb', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Ivar', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Ivar', u'subst', u'prop', u'mask', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Ivar subst prop mask <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'utmerket', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'utmerke', u'verb', u'pret', u'rl4', u'pr9'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'utmerke verb pret rl4 pr9', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'seg', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'seg', u'pron', u'akk', u'refl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'seg pron akk refl', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'likevel', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'likevel', u'adv'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'likevel adv', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ved', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ved', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ved prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'konfirmasjonen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'konfirmasjon', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'konfirmasjon subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj', u'clb'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj clb', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'presten', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'prest', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'prest subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'skrev', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'skrive', u'verb', u'pret', u'tr1', u'i1', u'tr11', u'pa1', u'd1', u'pa5', u'pa3'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'skrive verb pret tr1 i1 tr11 pa1 d1 pa5 pa3', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'rosende', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'rose', u'adj', u'<pres-part>', u'tr1', u'd5', u'rl9'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'rose adj <pres-part> tr1 d5 rl9', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'om', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'om', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'om prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ham', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'han', u'pron', u'mask', u'ent', u'pers', u'hum', u'3', u'akk'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'han pron mask ent pers hum 3 akk', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'i', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'i', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'i prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'kirkeboken', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'kirkebok', u'subst', u'appell', u'mask', u'be', u'ent', u'<*bok>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'kirkebok subst appell mask be ent <*bok>', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'G\xe5rden', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'g\xe5rd', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'g\xe5rd subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Ekset', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Ekset', u'subst', u'prop', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Ekset subst prop <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'med', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'med', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'med prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Sivert', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Sivert', u'subst', u'prop', u'mask', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Sivert subst prop mask <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Rasmus', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Rasmus', u'subst', u'prop', u'mask', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Rasmus subst prop mask <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Aarflots', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Aarflot', u'subst', u'prop', u'gen', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Aarflot subst prop gen <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'boksamling', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'boksamling', u'subst', u'appell', u'mask', u'ub', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'boksamling subst appell mask ub ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'var', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'v\xe6re', u'verb', u'pret', u'a5', u'pr1', u'pr2', u'<aux1/perf_part>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'v\xe6re verb pret a5 pr1 pr2 <aux1/perf_part>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'bare', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'bare', u'adv'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'bare adv', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'3', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': True, 'roman': False, 'quantity': True}, 'is_det': True, 'tagging': [u'3', u'det', u'fl', u'kvant'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'3 det fl kvant', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'kilometer', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'kilometer', u'subst', u'appell', u'mask', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'kilometer subst appell mask ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'fr\xe5', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'fr\xe5', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'fr\xe5 prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'\xc5sen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'\xc5sen', u'subst', u'prop', u'<*sen>', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'\xc5sen subst prop <*sen> <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'garden', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'gard', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'gard subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Aarflot', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Aarflot', u'subst', u'prop'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Aarflot subst prop', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'hadde', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ha', u'verb', u'pret', u'pa1', u'd5', u'a6', u'tr12', u'rl6', u'pa3', u'tr6', u'd6/til', u'<aux1/perf_part>', u'pa6'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ha verb pret pa1 d5 a6 tr12 rl6 pa3 tr6 d6/til <aux1/perf_part> pa6', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'selv', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'selv', u'adv', u'<*elv>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'selv adv <*elv>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'gjort', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'gj\xf8re', u'verb', u'perf-part', u'tr1', u'rl9', u'pr3'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'gj\xf8re verb perf-part tr1 rl9 pr3', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'observasjoner', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'observasjon', u'subst', u'appell', u'mask', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'observasjon subst appell mask ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'om', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'om', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'om prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'slektskap', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'slektskap', u'subst', u'appell', u'n\xf8yt', u'ub', u'fl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'slektskap subst appell n\xf8yt ub fl', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'mellom', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'mellom', u'prep'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'mellom prep', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'sunnm\xf8rsdialekten', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'sunnm\xf8rsdialekt', u'subst', u'appell', u'mask', u'be', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'sunnm\xf8rsdialekt subst appell mask be ent', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'gammelnorsk', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'gammelnorsk', u'adj', u'n\xf8yt', u'ub', u'ent', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'gammelnorsk adj n\xf8yt ub ent pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj', u'clb'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj clb', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'dette', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'dette', u'pron', u'n\xf8yt', u'ent', u'pers', u'3'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'dette pron n\xf8yt ent pers 3', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'kan', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'kunne', u'verb', u'pres', u'tr1', u'tr3', u'<aux1/infinitiv>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'kunne verb pres tr1 tr3 <aux1/infinitiv>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'ha', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ha', u'verb', u'inf', u'pa1', u'd5', u'a6', u'tr12', u'rl6', u'pa3', u'tr6', u'd6/til', u'<aux1/perf_part>', u'pa6'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'ha verb inf pa1 d5 a6 tr12 rl6 pa3 tr6 d6/til <aux1/perf_part> pa6', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'inspirert', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'inspirere', u'verb', u'perf-part', u'tr1'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'inspirere verb perf-part tr1', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'den', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': True, 'tagging': [u'den', u'det', u'dem', u'fem', u'ent'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'den det dem fem ent', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'unge', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'ung', u'adj', u'be', u'ent', u'pos'], 'is_conj': False, 'is_unknown': False, 'is_adj': True, 'is_interj': False, 'options': u'ung adj be ent pos', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Aasen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Aasen', u'subst', u'prop', u'<*sen>', u'<*>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Aasen subst prop <*sen> <*>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'Aasen', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'Aasen', u'subst', u'prop', u'<*sen>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'Aasen subst prop <*sen>', 'is_subst': True, 'is_prop': True},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'l\xe6rte', 'is_verb': True, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'l\xe6re', u'verb', u'pret', u'tr1', u'tr11', u'pa1', u'd5', u'tr2', u'd1', u'tr3', u'd3'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'l\xe6re verb pret tr1 tr11 pa1 d5 tr2 d1 tr3 d3', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'seg', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'seg', u'pron', u'akk', u'refl'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'seg pron akk refl', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'norr\xf8nt', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'norr\xf8nt', u'subst', u'appell', u'n\xf8yt', u'ub\xf8y'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'norr\xf8nt subst appell n\xf8yt ub\xf8y', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'engelsk', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'engelsk', u'subst', u'appell', u'n\xf8yt', u'ub\xf8y'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'engelsk subst appell n\xf8yt ub\xf8y', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u',', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$,', u'<komma>'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$, <komma>', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'fransk', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'fransk', u'subst', u'appell', u'n\xf8yt', u'ub\xf8y'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'fransk subst appell n\xf8yt ub\xf8y', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'og', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'og', u'konj'], 'is_conj': True, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'og konj', 'is_subst': False, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'latin', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'latin', u'subst', u'appell', u'n\xf8yt', u'ub\xf8y'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'latin subst appell n\xf8yt ub\xf8y', 'is_subst': True, 'is_prop': False},
                            {'is_inf_merke': False, 'is_sbu': False, 'word': u'.', 'is_verb': False, 'is_number': {'ordinal': False, 'is_number': False, 'roman': False, 'quantity': False}, 'is_det': False, 'tagging': [u'$.', u'clb', u'<<<', u'<punkt>', u'<<<'], 'is_conj': False, 'is_unknown': False, 'is_adj': False, 'is_interj': False, 'options': u'$. clb <<< <punkt> <<<', 'is_subst': False, 'is_prop': False}]}
# Stopwords
stopwords = [u'vart', u'over', u'skal', u'ikkje', u'deires', u'hennes', u'dere', u'henne', u'alle', u'han',
            u'begge', u'f\xf8r', u'ved', u'hvor', u'har', u'korso', u'oss', u'ditt', u'morgen', u'meget',
            u'opp', u'di', u'noe', u'de', u'mot', u'vere', u'noko', u'du', u'din', u'hossen', u'mykje',
            u'denne', u'etter', u'upp', u'ville', u'blitt', u'en', u'hvem', u'kunne', u'mi', u'skulle',
            u'nokon', u'kvifor', u'seg', u'bare', u'et', u'v\xe6re', u'blei', u'somt', u'inni', u'er',
            u'hvorfor', u'v\xe5r', u'ingi', u'for', u'ned', u'kun', u'bli', u'ble', u'deim', u'med', u'meg',
            u'd\xe5', u'mitt', u'men', u'fordi', u'hoss', u'nokre', u'hadde', u'sidan', u'ja', u'om', u'kveld',
            u'ett', u'og', u'ein', u'hennar', u'samme', u'hva', u'sj\xf8l', u'som', u'korleis', u'vil', u'dykkar',
            u'sist', u'middag', u'hvordan', u'fra', u'sine', u'kom', u'her', u'publisert', u'artikkeltags', u'kven',
            u'ingen', u'n\xe5', u'varte', u'ikke', u'deira', u'noen', u'jeg', u'var', u'n\xe5r', u'v\xe6rt', u'mellom',
            u'uten', u'hun', u'honom', u'dersom', u'mine', u'tilsammen', u'hvilken', u'ho', u'ha', u'kvar', u'me', u'hj\xe5',
            u'inkje', u'verte', u'\xe5', u'eit', u'b\xe5de', u'ut', u'der', u'det', u'um', u'dei', u'dykk', u'dem', u'den',
            u's\xe5', u'deg', u'eg', u'vors', u'vi', u'slik', u'vort', u'inn', u'blir', u'at', u'av', u'sitt', u'vore', u'hver',
            u's\xe5nn', u'min', u'elles', u'eller', u'deres', u'enn', u'hvilke', u'til', u'sia', u'disse', u'p\xe5', u'nokor',
            u'selv', u'sin', u'hvis', u'siden', u'eitt', u'ogs\xe5', u'kva', u'dette', u'kan', u'kvi', u'hoe',
            u'superparet', u'hans', u'kvarhelst', u'da', u'medan', u'man', u'somme', u'i', u'no', u'b\xe5e', u'si',
            u'so', u'noka', u'mange']
class NERPosNoTestCase(unittest.TestCase):
    nerposno = None
    currentDirectory = currentDirectory = "%s" % (os.path.dirname(os.path.realpath(__file__)), )
    testTextsDirectory = "%s/../../../data/text/" % (currentDirectory, )

    def setUp(self):
        self.nerposno = NERPosNo()

    def tearDown(self):
        self.nerposno = None

    def test__nerposno_text_analysis_is_none(self):
        """
        Check if the text analysis input is none
        """
        input = None
        self.assertRaises(Exception, self.nerposno.findNER, input)

    def test__nerposno_text_analysis_is_not_dict(self):
        """
        Check if the text analysis input is not a dict
        """
        input = "String"
        self.assertRaises(Exception, self.nerposno.findNER, input)

        input = 1
        self.assertRaises(Exception, self.nerposno.findNER, input)

        input = True
        self.assertRaises(Exception, self.nerposno.findNER, input)

    def test__nerposno_text_analysis_without_required_key(self):
        """
        Check if the text analysis contains the key 'obt'
        """
        input = {}
        self.assertRaises(Exception, self.nerposno.findNER, input)

    def test__nerposno_text_analysis_without_stopwords(self):
        """
        Check findNER with a valid text analysis and no stopwords
        """
        input = text_analysis
        stopwords = []
        actual = self.nerposno.findNER(input, stopwords)
        expected = [u'Rasmus Aarflots', u'Bibelen', u'\xabIvar\xbb', u'Aasen', u'Aarflot',
                    u'Ivar Aasen', u'Sivert', u'Sunnm\xf8re', u'Ivar Jonsson', u'Ekset', u'\xc5sen',
                    u'Iver Andreas', u'Ivar', u'Hovdebygda']

        self.assertEquals(actual, expected)

    def test__nerposno_text_analysis_with_stopwords(self):
        """
        Check findNER with a valid text analysis and  stopwords
        """
        input = text_analysis

        actual = self.nerposno.findNER(input, stopwords)
        expected = [u'Rasmus Aarflots', u'Bibelen', u'\xabIvar\xbb', u'Aasen', u'Aarflot',
                    u'Ivar Aasen', u'Sivert', u'Sunnm\xf8re', u'Ivar Jonsson', u'Ekset', u'\xc5sen',
                    u'Iver Andreas', u'Ivar', u'Hovdebygda']

        self.assertEquals(actual, expected)
